apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-edit
  namespace: netlify-edit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.0
          ports:
            - containerPort: 80
metadata.name: nginx-name-edited
metadata.namespace: netlify-other
"spec.template.spec.containers[0].image": nginx:1.14.0
