backend:
  name: github
  repo: triangle-stream/Netlify-test  # Replace with your repo details

media_folder: "media"

collections:
  - name: "config"
    label: "Deployment Config"
    files:
      - name: "nginx"
        label: "Nginx Deployment"
        file: "k8s/nginx-deployment.yaml"
        fields:
          - label: "Metadata"
            name: "metadata"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Namespace", name: "namespace", widget: "string" }
          - label: "Spec"
            name: "spec"
            widget: "object"
            fields:
              - label: "Template"
                name: "template"
                widget: "object"
                fields:
                  - label: "Spec"
                    name: "spec"
                    widget: "object"
                    fields:
                      - label: "Containers"
                        name: "containers"
                        widget: "list"
                        fields:
                          - label: "Image"
                            name: "image"
                            widget: "string"

