backend:
  name: github
  repo: triangle-stream/Netlify-test  # Replace with your repo details

media_folder: "media"

collections:
  - name: "config"
    label: "Nginx Deployment Configuration"
    files:
      - label: "Nginx Configuration"
        name: "nginx_config"
        file: "k8s/nginx-deployment.yaml"  # Adjust the path
        fields:
          - label: "Deployment Name"
            name: "metadata.name"
            widget: "string"
          - label: "Namespace"
            name: "metadata.namespace"
            widget: "string"
          - label: "Container Image"
            name: "spec.template.spec.containers[0].image"
            widget: "string"

